source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

platform :ios, '9.0'
# 引用框架
use_frameworks!
# ignore all warnings from all pods(注解)
inhibit_all_warnings!
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewToday' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 # Pods for Pos
 pod 'Alamofire'
 pod 'SwiftyJSON'
 pod 'SnapKit'
 #pod 'Bugly'
 
end
#Xcode里配置：项目名->Target->Build Settings->Enable BitCode中设置为NO就可以了.
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end
